<a href="https://colab.research.google.com/github/SachinScaler/Apr24_TimeSeries_and_RecSys/blob/main/Pandas_4%7CLecture.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!gdown 1s2TkjSpzNc4SyxqRrQleZyDIHlc7bxnd
!gdown 1Ws-_s1fHZ9nHfGLVUQurbHDvStePlEJm

Downloading...
From: https://drive.google.com/uc?id=1s2TkjSpzNc4SyxqRrQleZyDIHlc7bxnd
To: /content/movies.csv
100% 112k/112k [00:00<00:00, 14.6MB/s]
Downloading...
From: https://drive.google.com/uc?id=1Ws-_s1fHZ9nHfGLVUQurbHDvStePlEJm
To: /content/directors.csv
100% 65.4k/65.4k [00:00<00:00, 5.02MB/s]

In [3]:
import pandas as pd
import numpy as np

movies = pd.read_csv('movies.csv', index_col=0)
directors = pd.read_csv('directors.csv', index_col=0)

data = movies.merge(directors, how='left', left_on='director_id', right_on='id')
data.drop(['director_id','id_y'], axis=1, inplace=True)

- Productivity: num_movies/num_year
    - no of movies
    - number of years:(max-year - min -year)
        - min_year
        - max_year

In [4]:
data_agg = data.groupby(['director_name']) \
            [["year", "title"]].aggregate(
                {"year":['min','max'], "title": "count"}
                )
data_agg

                             year       title
                              min   max count
director_name
Adam McKay                   2004  2015     6
Adam Shankman                2001  2012     8
Alejandro González Iñárritu  2000  2015     6
Alex Proyas                  1994  2016     5
Alexander Payne              1999  2013     5
...                           ...   ...   ...
Wes Craven                   1984  2011    10
Wolfgang Petersen            1981  2006     7
Woody Allen                  1977  2013    18
Zack Snyder                  2004  2016     7
Zhang Yimou                  2002  2014     6

[199 rows x 3 columns]

In [7]:
data_agg['year']

                              min   max
director_name
Adam McKay                   2004  2015
Adam Shankman                2001  2012
Alejandro González Iñárritu  2000  2015
Alex Proyas                  1994  2016
Alexander Payne              1999  2013
...                           ...   ...
Wes Craven                   1984  2011
Wolfgang Petersen            1981  2006
Woody Allen                  1977  2013
Zack Snyder                  2004  2016
Zhang Yimou                  2002  2014

[199 rows x 2 columns]

- multi-indexing: more than one level of index

['year']['max'] -> ['year_max']

In [8]:
data.columns

Index(['id_x', 'budget', 'popularity', 'revenue', 'title', 'vote_average',
       'vote_count', 'year', 'month', 'day', 'director_name', 'gender'],
      dtype='object')

In [9]:
data_agg.columns

MultiIndex([( 'year',   'min'),
            ( 'year',   'max'),
            ('title', 'count')],
           )

In [12]:
new_cols = [year + '_' + agg for year, agg in data_agg.columns]
new_cols

['year_min', 'year_max', 'title_count']

In [13]:
data_agg.columns = new_cols
data_agg

                             year_min  year_max  title_count
director_name
Adam McKay                       2004      2015            6
Adam Shankman                    2001      2012            8
Alejandro González Iñárritu      2000      2015            6
Alex Proyas                      1994      2016            5
Alexander Payne                  1999      2013            5
...                               ...       ...          ...
Wes Craven                       1984      2011           10
Wolfgang Petersen                1981      2006            7
Woody Allen                      1977      2013           18
Zack Snyder                      2004      2016            7
Zhang Yimou                      2002      2014            6

[199 rows x 3 columns]

inbuilt method from groupby:
 in agg:
    - col_name = ('col_to_agg', 'aggop',

In [14]:
data.groupby('director_name')[['year', 'title']].aggregate(
    year_max=('year','max'),
    year_min=('year','min'),
    title_count=('title','count')
)

                             year_max  year_min  title_count
director_name
Adam McKay                       2015      2004            6
Adam Shankman                    2012      2001            8
Alejandro González Iñárritu      2015      2000            6
Alex Proyas                      2016      1994            5
Alexander Payne                  2013      1999            5
...                               ...       ...          ...
Wes Craven                       2011      1984           10
Wolfgang Petersen                2006      1981            7
Woody Allen                      2013      1977           18
Zack Snyder                      2016      2004            7
Zhang Yimou                      2014      2002            6

[199 rows x 3 columns]

In [16]:
data.groupby(['director_name'])[["year", "title"]].aggregate(
            {"year":['min','max'], "title": "count"}
                )

                             year       title
                              min   max count
director_name
Adam McKay                   2004  2015     6
Adam Shankman                2001  2012     8
Alejandro González Iñárritu  2000  2015     6
Alex Proyas                  1994  2016     5
Alexander Payne              1999  2013     5
...                           ...   ...   ...
Wes Craven                   1984  2011    10
Wolfgang Petersen            1981  2006     7
Woody Allen                  1977  2013    18
Zack Snyder                  2004  2016     7
Zhang Yimou                  2002  2014     6

[199 rows x 3 columns]

In [15]:
data.head()

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male
2,43599,245000000,107,880674609,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,Male

HW: Set director_name and year together as index

In [17]:
!gdown 173A59xh2mnpmljCCB9bhC4C5eP2IS6qZ

Downloading...
From: https://drive.google.com/uc?id=173A59xh2mnpmljCCB9bhC4C5eP2IS6qZ
To: /content/Pfizer_1.csv
100% 1.51k/1.51k [00:00<00:00, 6.22MB/s]

In [18]:
data = pd.read_csv('Pfizer_1.csv')
data.head()

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,23.0,22.0,NaN,21.0,21.0,22,23.0,21.0,22.0,20,20.0,21
1,15-10-2020,diltiazem hydrochloride,Pressure,12.0,13.0,NaN,11.0,13.0,14,16.0,16.0,24.0,18,19.0,20
2,15-10-2020,docetaxel injection,Temperature,NaN,17.0,18.0,NaN,17.0,18,NaN,NaN,23.0,23,25.0,25
3,15-10-2020,docetaxel injection,Pressure,NaN,22.0,22.0,NaN,22.0,23,NaN,NaN,27.0,26,29.0,28
4,15-10-2020,ketamine hydrochloride,Temperature,24.0,NaN,NaN,27.0,NaN,26,25.0,24.0,23.0,22,21.0,20

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 15 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       18 non-null     object
 1   Drug_Name  18 non-null     object
 2   Parameter  18 non-null     object
 3   1:30:00    16 non-null     float64
 4   2:30:00    16 non-null     float64
 5   3:30:00    12 non-null     float64
 6   4:30:00    14 non-null     float64
 7   5:30:00    16 non-null     float64
 8   6:30:00    18 non-null     int64
 9   7:30:00    16 non-null     float64
 10  8:30:00    14 non-null     float64
 11  9:30:00    16 non-null     float64
 12  10:30:00   18 non-null     int64
 13  11:30:00   16 non-null     float64
 14  12:30:00   18 non-null     int64
dtypes: float64(9), int64(3), object(3)
memory usage: 2.2+ KB

In [91]:
data.isna().sum() # pandas 5

Date         0
Drug_Name    0
Parameter    0
1:30:00      2
2:30:00      2
3:30:00      6
4:30:00      4
5:30:00      2
6:30:00      0
7:30:00      2
8:30:00      4
9:30:00      2
10:30:00     0
11:30:00     2
12:30:00     0
dtype: int64

- melting

In [25]:
pd.melt(data, id_vars=['Date', 'Parameter', 'Drug_Name'])

           Date    Parameter                Drug_Name  variable  value
0    15-10-2020  Temperature  diltiazem hydrochloride   1:30:00   23.0
1    15-10-2020     Pressure  diltiazem hydrochloride   1:30:00   12.0
2    15-10-2020  Temperature      docetaxel injection   1:30:00    NaN
3    15-10-2020     Pressure      docetaxel injection   1:30:00    NaN
4    15-10-2020  Temperature   ketamine hydrochloride   1:30:00   24.0
..          ...          ...                      ...       ...    ...
211  17-10-2020     Pressure  diltiazem hydrochloride  12:30:00   14.0
212  17-10-2020  Temperature      docetaxel injection  12:30:00   23.0
213  17-10-2020     Pressure      docetaxel injection  12:30:00   28.0
214  17-10-2020  Temperature   ketamine hydrochloride  12:30:00   24.0
215  17-10-2020     Pressure   ketamine hydrochloride  12:30:00   15.0

[216 rows x 5 columns]

In [27]:
data_melt = pd.melt(data,
                    id_vars = ['Date', 'Drug_Name', 'Parameter'],
                    var_name = "time",
                    value_name = 'reading')
data_melt

           Date                Drug_Name    Parameter      time  reading
0    15-10-2020  diltiazem hydrochloride  Temperature   1:30:00     23.0
1    15-10-2020  diltiazem hydrochloride     Pressure   1:30:00     12.0
2    15-10-2020      docetaxel injection  Temperature   1:30:00      NaN
3    15-10-2020      docetaxel injection     Pressure   1:30:00      NaN
4    15-10-2020   ketamine hydrochloride  Temperature   1:30:00     24.0
..          ...                      ...          ...       ...      ...
211  17-10-2020  diltiazem hydrochloride     Pressure  12:30:00     14.0
212  17-10-2020      docetaxel injection  Temperature  12:30:00     23.0
213  17-10-2020      docetaxel injection     Pressure  12:30:00     28.0
214  17-10-2020   ketamine hydrochloride  Temperature  12:30:00     24.0
215  17-10-2020   ketamine hydrochloride     Pressure  12:30:00     15.0

[216 rows x 5 columns]

In [30]:
data_melt[data_melt['Drug_Name']=='diltiazem hydrochloride']

           Date                Drug_Name    Parameter      time  reading
0    15-10-2020  diltiazem hydrochloride  Temperature   1:30:00     23.0
1    15-10-2020  diltiazem hydrochloride     Pressure   1:30:00     12.0
6    16-10-2020  diltiazem hydrochloride  Temperature   1:30:00     34.0
7    16-10-2020  diltiazem hydrochloride     Pressure   1:30:00     18.0
12   17-10-2020  diltiazem hydrochloride  Temperature   1:30:00     20.0
..          ...                      ...          ...       ...      ...
199  15-10-2020  diltiazem hydrochloride     Pressure  12:30:00     20.0
204  16-10-2020  diltiazem hydrochloride  Temperature  12:30:00     42.0
205  16-10-2020  diltiazem hydrochloride     Pressure  12:30:00     27.0
210  17-10-2020  diltiazem hydrochloride  Temperature  12:30:00     10.0
211  17-10-2020  diltiazem hydrochloride     Pressure  12:30:00     14.0

[72 rows x 5 columns]

In [28]:
data.head()

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,23.0,22.0,NaN,21.0,21.0,22,23.0,21.0,22.0,20,20.0,21
1,15-10-2020,diltiazem hydrochloride,Pressure,12.0,13.0,NaN,11.0,13.0,14,16.0,16.0,24.0,18,19.0,20
2,15-10-2020,docetaxel injection,Temperature,NaN,17.0,18.0,NaN,17.0,18,NaN,NaN,23.0,23,25.0,25
3,15-10-2020,docetaxel injection,Pressure,NaN,22.0,22.0,NaN,22.0,23,NaN,NaN,27.0,26,29.0,28
4,15-10-2020,ketamine hydrochloride,Temperature,24.0,NaN,NaN,27.0,NaN,26,25.0,24.0,23.0,22,21.0,20

### Can we use a list of columns like ["Date", "Parameter"] for the var_name parameter in pd.melt() on our Pfizer dataset?

In [35]:
pd.melt(data,
        id_vars = ['Date', 'Drug_Name', 'Parameter'],
        var_name = "time", # ["Date", "Parameter"] not possible
        value_name = 'reading')

           Date                Drug_Name    Parameter      time  reading
0    15-10-2020  diltiazem hydrochloride  Temperature   1:30:00     23.0
1    15-10-2020  diltiazem hydrochloride     Pressure   1:30:00     12.0
2    15-10-2020      docetaxel injection  Temperature   1:30:00      NaN
3    15-10-2020      docetaxel injection     Pressure   1:30:00      NaN
4    15-10-2020   ketamine hydrochloride  Temperature   1:30:00     24.0
..          ...                      ...          ...       ...      ...
211  17-10-2020  diltiazem hydrochloride     Pressure  12:30:00     14.0
212  17-10-2020      docetaxel injection  Temperature  12:30:00     23.0
213  17-10-2020      docetaxel injection     Pressure  12:30:00     28.0
214  17-10-2020   ketamine hydrochloride  Temperature  12:30:00     24.0
215  17-10-2020   ketamine hydrochloride     Pressure  12:30:00     15.0

[216 rows x 5 columns]

In [36]:
# data.columns = list_of_cols
data_melt

           Date                Drug_Name    Parameter      time  reading
0    15-10-2020  diltiazem hydrochloride  Temperature   1:30:00     23.0
1    15-10-2020  diltiazem hydrochloride     Pressure   1:30:00     12.0
2    15-10-2020      docetaxel injection  Temperature   1:30:00      NaN
3    15-10-2020      docetaxel injection     Pressure   1:30:00      NaN
4    15-10-2020   ketamine hydrochloride  Temperature   1:30:00     24.0
..          ...                      ...          ...       ...      ...
211  17-10-2020  diltiazem hydrochloride     Pressure  12:30:00     14.0
212  17-10-2020      docetaxel injection  Temperature  12:30:00     23.0
213  17-10-2020      docetaxel injection     Pressure  12:30:00     28.0
214  17-10-2020   ketamine hydrochloride  Temperature  12:30:00     24.0
215  17-10-2020   ketamine hydrochloride     Pressure  12:30:00     15.0

[216 rows x 5 columns]

Let's try to get our original df back

In [49]:
data_pivot = data_melt.pivot(
    index=['Date','Drug_Name','Parameter'],  # Columns used to make new frame’s index
    columns='time',   # Column used to make new frame’s columns
    values='reading'    # Column used for populating new frame’s values.
    )

In [50]:
data_pivot

time                                            10:30:00  11:30:00  12:30:00  \
Date       Drug_Name               Parameter
15-10-2020 diltiazem hydrochloride Pressure         18.0      19.0      20.0
                                   Temperature      20.0      20.0      21.0
           docetaxel injection     Pressure         26.0      29.0      28.0
                                   Temperature      23.0      25.0      25.0
           ketamine hydrochloride  Pressure          9.0       9.0      11.0
                                   Temperature      22.0      21.0      20.0
16-10-2020 diltiazem hydrochloride Pressure         24.0       NaN      27.0
                                   Temperature      40.0       NaN      42.0
           docetaxel injection     Pressure         28.0      29.0      30.0
                                   Temperature      56.0      57.0      58.0
           ketamine hydrochloride  Pressure         16.0      17.0      18.0
                                   Temperature      13.0      14.0      15.0
17-10-2020 diltiazem hydrochloride Pressure         11.0      13.0      14.0
                                   Temperature      14.0      11.0      10.0
           docetaxel injection     Pressure         28.0      29.0      28.0
                                   Temperature      21.0      22.0      23.0
           ketamine hydrochloride  Pressure         13.0      14.0      15.0
                                   Temperature      22.0      23.0      24.0

time                                            1:30:00  2:30:00  3:30:00  \
Date       Drug_Name               Parameter
15-10-2020 diltiazem hydrochloride Pressure        12.0     13.0      NaN
                                   Temperature     23.0     22.0      NaN
           docetaxel injection     Pressure         NaN     22.0     22.0
                                   Temperature      NaN     17.0     18.0
           ketamine hydrochloride  Pressure         8.0      NaN      NaN
                                   Temperature     24.0      NaN      NaN
16-10-2020 diltiazem hydrochloride Pressure        18.0     19.0     20.0
                                   Temperature     34.0     35.0     36.0
           docetaxel injection     Pressure        23.0     24.0      NaN
                                   Temperature     46.0     47.0      NaN
           ketamine hydrochloride  Pressure        12.0     12.0     13.0
                                   Temperature      8.0      9.0     10.0
17-10-2020 diltiazem hydrochloride Pressure         3.0      4.0      4.0
                                   Temperature     20.0     19.0     19.0
           docetaxel injection     Pressure        20.0     22.0     22.0
                                   Temperature     12.0     13.0     14.0
           ketamine hydrochloride  Pressure         8.0      9.0     10.0
                                   Temperature     13.0     14.0     15.0

time                                            4:30:00  5:30:00  6:30:00  \
Date       Drug_Name               Parameter
15-10-2020 diltiazem hydrochloride Pressure        11.0     13.0     14.0
                                   Temperature     21.0     21.0     22.0
           docetaxel injection     Pressure         NaN     22.0     23.0
                                   Temperature      NaN     17.0     18.0
           ketamine hydrochloride  Pressure         7.0      NaN      9.0
                                   Temperature     27.0      NaN     26.0
16-10-2020 diltiazem hydrochloride Pressure        21.0     22.0     23.0
                                   Temperature     36.0     37.0     38.0
           docetaxel injection     Pressure        25.0     26.0     27.0
                                   Temperature     48.0     48.0     49.0
           ketamine hydrochloride  Pressure         NaN     15.0     15.0
                                   Temperature      NaN     11.0     12.0
17-10-2020 diltiazem hydrochloride Pressure         4.0      6.0      8.0
                                   Temperature     18.0     17.0     16.0
           docetaxel injection     Pressure        22.0     22.0     23.0
                                   Temperature     15.0     16.0     17.0
           ketamine hydrochloride  Pressure        11.0     11.0     12.0
                                   Temperature     16.0     17.0     18.0

time                                            7:30:00  8:30:00  9:30:00
Date       Drug_Name               Parameter
15-10-2020 diltiazem hydrochloride Pressure        16.0     16.0     24.0
                                   Temperature     23.0     21.0     22.0
           docetaxel injection     Pressure         NaN      NaN     27.0
                                   Temperature      NaN      NaN     23.0
           ketamine hydrochloride  Pressure        10.0     11.0     10.0
                                   Temperature     25.0     24.0     23.0
16-10-2020 diltiazem hydrochloride Pressure        24.0     25.0     25.0
                                   Temperature     37.0     38.0     39.0
           docetaxel injection     Pressure        28.0     29.0     28.0
                                   Temperature     50.0     52.0     55.0
           ketamine hydrochloride  Pressure        15.0     15.0      NaN
                                   Temperature     12.0     11.0      NaN
17-10-2020 diltiazem hydrochloride Pressure         9.0      NaN      9.0
                                   Temperature     15.0      NaN     13.0
           docetaxel injection     Pressure        25.0     26.0     27.0
                                   Temperature     18.0     19.0     20.0
           ketamine hydrochloride  Pressure        12.0     11.0     12.0
                                   Temperature     19.0     20.0     21.0

In [51]:
data_tidy = data_pivot.reset_index()
data_tidy

time,Date,Drug_Name,Parameter,10:30:00,11:30:00,12:30:00,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00
0,15-10-2020,diltiazem hydrochloride,Pressure,18.0,19.0,20.0,12.0,13.0,NaN,11.0,13.0,14.0,16.0,16.0,24.0
1,15-10-2020,diltiazem hydrochloride,Temperature,20.0,20.0,21.0,23.0,22.0,NaN,21.0,21.0,22.0,23.0,21.0,22.0
2,15-10-2020,docetaxel injection,Pressure,26.0,29.0,28.0,NaN,22.0,22.0,NaN,22.0,23.0,NaN,NaN,27.0
3,15-10-2020,docetaxel injection,Temperature,23.0,25.0,25.0,NaN,17.0,18.0,NaN,17.0,18.0,NaN,NaN,23.0
4,15-10-2020,ketamine hydrochloride,Pressure,9.0,9.0,11.0,8.0,NaN,NaN,7.0,NaN,9.0,10.0,11.0,10.0
5,15-10-2020,ketamine hydrochloride,Temperature,22.0,21.0,20.0,24.0,NaN,NaN,27.0,NaN,26.0,25.0,24.0,23.0
6,16-10-2020,diltiazem hydrochloride,Pressure,24.0,NaN,27.0,18.0,19.0,20.0,21.0,22.0,23.0,24.0,25.0,25.0
7,16-10-2020,diltiazem hydrochloride,Temperature,40.0,NaN,42.0,34.0,35.0,36.0,36.0,37.0,38.0,37.0,38.0,39.0
8,16-10-2020,docetaxel injection,Pressure,28.0,29.0,30.0,23.0,24.0,NaN,25.0,26.0,27.0,28.0,29.0,28.0
9,16-10-2020,docetaxel injection,Temperature,56.0,57.0,58.0,46.0,47.0,NaN,48.0,48.0,49.0,50.0,52.0,55.0
10,16-10-2020,ketamine hydrochloride,Pressure,16.0,17.0,18.0,12.0,12.0,13.0,NaN,15.0,15.0,15.0,15.0,NaN
11,16-10-2020,ketamine hydrochloride,Temperature,13.0,14.0,15.0,8.0,9.0,10.0,NaN,11.0,12.0,12.0,11.0,NaN
12,17-10-2020,diltiazem hydrochloride,Pressure,11.0,13.0,14.0,3.0,4.0,4.0,4.0,6.0,8.0,9.0,NaN,9.0
13,17-10-2020,diltiazem hydrochloride,Temperature,14.0,11.0,10.0,20.0,19.0,19.0,18.0,17.0,16.0,15.0,NaN,13.0
14,17-10-2020,docetaxel injection,Pressure,28.0,29.0,28.0,20.0,22.0,22.0,22.0,22.0,23.0,25.0,26.0,27.0
15,17-10-2020,docetaxel injection,Temperature,21.0,22.0,23.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,20.0
16,17-10-2020,ketamine hydrochloride,Pressure,13.0,14.0,15.0,8.0,9.0,10.0,11.0,11.0,12.0,12.0,11.0,12.0
17,17-10-2020,ketamine hydrochloride,Temperature,22.0,23.0,24.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,20.0,21.0

In [41]:
data_pivot.loc['16-10-2020']

time                                 10:30:00  11:30:00  12:30:00  1:30:00  \
Drug_Name               Parameter
diltiazem hydrochloride Pressure         24.0       NaN      27.0     18.0
                        Temperature      40.0       NaN      42.0     34.0
docetaxel injection     Pressure         28.0      29.0      30.0     23.0
                        Temperature      56.0      57.0      58.0     46.0
ketamine hydrochloride  Pressure         16.0      17.0      18.0     12.0
                        Temperature      13.0      14.0      15.0      8.0

time                                 2:30:00  3:30:00  4:30:00  5:30:00  \
Drug_Name               Parameter
diltiazem hydrochloride Pressure        19.0     20.0     21.0     22.0
                        Temperature     35.0     36.0     36.0     37.0
docetaxel injection     Pressure        24.0      NaN     25.0     26.0
                        Temperature     47.0      NaN     48.0     48.0
ketamine hydrochloride  Pressure        12.0     13.0      NaN     15.0
                        Temperature      9.0     10.0      NaN     11.0

time                                 6:30:00  7:30:00  8:30:00  9:30:00
Drug_Name               Parameter
diltiazem hydrochloride Pressure        23.0     24.0     25.0     25.0
                        Temperature     38.0     37.0     38.0     39.0
docetaxel injection     Pressure        27.0     28.0     29.0     28.0
                        Temperature     49.0     50.0     52.0     55.0
ketamine hydrochloride  Pressure        15.0     15.0     15.0      NaN
                        Temperature     12.0     12.0     11.0      NaN

In [42]:
data_pivot.loc['16-10-2020'].loc['diltiazem hydrochloride']

time,10:30:00,11:30:00,12:30:00,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00
Parameter,,,,,,,,,,,,
Pressure,24.0,NaN,27.0,18.0,19.0,20.0,21.0,22.0,23.0,24.0,25.0,25.0
Temperature,40.0,NaN,42.0,34.0,35.0,36.0,36.0,37.0,38.0,37.0,38.0,39.0

### Break HW

try this and explain what is teh problem with this code:

Q1: Can you pivot the melted data and convert Parameter values as columns?
You can store the output in data_tidy

Q2: What is the issue with following code:
```
data_tidy.pivot(index=['Drug_Name'],
columns = 'Date',
values=['Temperature'])

```

In [53]:
data_melt

           Date                Drug_Name    Parameter      time  reading
0    15-10-2020  diltiazem hydrochloride  Temperature   1:30:00     23.0
1    15-10-2020  diltiazem hydrochloride     Pressure   1:30:00     12.0
2    15-10-2020      docetaxel injection  Temperature   1:30:00      NaN
3    15-10-2020      docetaxel injection     Pressure   1:30:00      NaN
4    15-10-2020   ketamine hydrochloride  Temperature   1:30:00     24.0
..          ...                      ...          ...       ...      ...
211  17-10-2020  diltiazem hydrochloride     Pressure  12:30:00     14.0
212  17-10-2020      docetaxel injection  Temperature  12:30:00     23.0
213  17-10-2020      docetaxel injection     Pressure  12:30:00     28.0
214  17-10-2020   ketamine hydrochloride  Temperature  12:30:00     24.0
215  17-10-2020   ketamine hydrochloride     Pressure  12:30:00     15.0

[216 rows x 5 columns]

In [62]:
data_tidy = data_melt.pivot(
    index=['Date','Drug_Name','time'],  # Columns used to make new frame’s index
    columns='Parameter',   # Column used to make new frame’s columns
    values='reading'    # Column used for populating new frame’s values.
    ).reset_index()
data_tidy

Parameter,Date,Drug_Name,time,Pressure,Temperature
0,15-10-2020,diltiazem hydrochloride,10:30:00,18.0,20.0
1,15-10-2020,diltiazem hydrochloride,11:30:00,19.0,20.0
2,15-10-2020,diltiazem hydrochloride,12:30:00,20.0,21.0
3,15-10-2020,diltiazem hydrochloride,1:30:00,12.0,23.0
4,15-10-2020,diltiazem hydrochloride,2:30:00,13.0,22.0
...,...,...,...,...,...
103,17-10-2020,ketamine hydrochloride,5:30:00,11.0,17.0
104,17-10-2020,ketamine hydrochloride,6:30:00,12.0,18.0
105,17-10-2020,ketamine hydrochloride,7:30:00,12.0,19.0
106,17-10-2020,ketamine hydrochloride,8:30:00,11.0,20.0
107,17-10-2020,ketamine hydrochloride,9:30:00,12.0,21.0

In [60]:
data_tidy[data_tidy['Drug_Name']=='diltiazem hydrochloride'].Pressure.head()

0    18.0
1    19.0
2    20.0
3    12.0
4    13.0
Name: Pressure, dtype: float64

In [63]:
data_tidy.head()

Parameter,Date,Drug_Name,time,Pressure,Temperature
0,15-10-2020,diltiazem hydrochloride,10:30:00,18.0,20.0
1,15-10-2020,diltiazem hydrochloride,11:30:00,19.0,20.0
2,15-10-2020,diltiazem hydrochloride,12:30:00,20.0,21.0
3,15-10-2020,diltiazem hydrochloride,1:30:00,12.0,23.0
4,15-10-2020,diltiazem hydrochloride,2:30:00,13.0,22.0

In [69]:
data_tidy.pivot(index=['Drug_Name'],
                columns = 'Date',
                values=['Temperature'],
                )

ValueError: Index contains duplicate entries, cannot reshape

In [68]:
pd.pivot_table(data_tidy,
               index='Drug_Name',
               columns='Date',
               values=['Temperature'],
               aggfunc=np.mean) # Duplicate index will be aggregated

<ipython-input-68-3614561f2139>:1: FutureWarning: The provided callable <function mean at 0x79a8b1d17d90> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pd.pivot_table(data_tidy,

Parameter               Temperature
Date                     15-10-2020 16-10-2020 17-10-2020
Drug_Name
diltiazem hydrochloride   21.454545  37.454545  15.636364
docetaxel injection       20.750000  51.454545  17.500000
ketamine hydrochloride    23.555556  11.500000  18.500000

In [70]:
data_tidy.head()

Parameter,Date,Drug_Name,time,Pressure,Temperature
0,15-10-2020,diltiazem hydrochloride,10:30:00,18.0,20.0
1,15-10-2020,diltiazem hydrochloride,11:30:00,19.0,20.0
2,15-10-2020,diltiazem hydrochloride,12:30:00,20.0,21.0
3,15-10-2020,diltiazem hydrochloride,1:30:00,12.0,23.0
4,15-10-2020,diltiazem hydrochloride,2:30:00,13.0,22.0

In [74]:
data_tidy.Temperature.min()

8.0

In [73]:
data_tidy.Temperature.max()

58.0

In [ ]:
temp_points = [5, 20, 35, 50, 60]

temp_labels = ['low','medium','high','very_high'] # labels define the severity of the resultant output of the

In [79]:
def func_cat(x):
    if 5 < x <=20:
        return "low"
    elif 20 < x <= 35:
        return "medium"
    elif 35 < x <= 50:
        return "high"
    else:
        return "very_high"

data_tidy['label_with_apply'] = data_tidy.Temperature.apply(func_cat)
data_tidy.head()

Parameter,Date,Drug_Name,time,Pressure,Temperature,label_with_apply
0,15-10-2020,diltiazem hydrochloride,10:30:00,18.0,20.0,low
1,15-10-2020,diltiazem hydrochloride,11:30:00,19.0,20.0,low
2,15-10-2020,diltiazem hydrochloride,12:30:00,20.0,21.0,medium
3,15-10-2020,diltiazem hydrochloride,1:30:00,12.0,23.0,medium
4,15-10-2020,diltiazem hydrochloride,2:30:00,13.0,22.0,medium

In [77]:
# x = 20
# 5 < x <= 20

### Binning

In [80]:
temp_points = [5, 20, 35, 50, 60]

temp_labels = ['low','medium','high','very_high'] # labels define the severity of the resultant output of the test

data_tidy['temp_cat'] = pd.cut(data_tidy['Temperature'], # col on which bin to be performed
                               bins=temp_points, # bin values as list
                               labels=temp_labels) # label_values to be created
data_tidy.head()

Parameter,Date,Drug_Name,time,Pressure,Temperature,label_with_apply,temp_cat
0,15-10-2020,diltiazem hydrochloride,10:30:00,18.0,20.0,low,low
1,15-10-2020,diltiazem hydrochloride,11:30:00,19.0,20.0,low,low
2,15-10-2020,diltiazem hydrochloride,12:30:00,20.0,21.0,medium,medium
3,15-10-2020,diltiazem hydrochloride,1:30:00,12.0,23.0,medium,medium
4,15-10-2020,diltiazem hydrochloride,2:30:00,13.0,22.0,medium,medium

In [ ]:
def func_cat(x):
    if 5 < x <= 20:
        return "low"
    elif 20 < x <= 35:
        return "medium"
    elif 35 < x <= 50:
        return "high"
    else:
        return "very_high"

https://www.scaler.com/hire/test/problem/101485/

In [83]:
data_tidy['Temperature'].fillna(1) # replace nan with 0

0      20.0
1      20.0
2      21.0
3      23.0
4      22.0
       ...
103    17.0
104    18.0
105    19.0
106    20.0
107    21.0
Name: Temperature, Length: 108, dtype: float64

```
| -> or
& -> and

```

In [84]:
# mask = (df['Stream']=='Commerce') | (df['Stream']=='Arts'))

# df_new = df[mask]
# mask = df_new['Percentage'] >=75
# df_new = df_new[mask]

In [85]:
df = pd.DataFrame({"Gender": ["M", "F", "M"]})
df

  Gender
0      M
1      F
2      M

In [90]:
df['Gender'].map({'M':0, 'F':1}) #

0    0
1    1
2    0
Name: Gender, dtype: int64

In [ ]:
#

Filtering on Groups: